name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código com suporte ao Git LFS
        uses: actions/checkout@v4
        with:
          lfs: true # Garante que o arquivo grande de mais de 100MB seja baixado no runner

      - name: Build da imagem Docker
        run: docker build -t test-container .

      - name: Rodar testes dentro do Docker
        run: docker run --rm test-container npm test